feature
2060-io/trust-service-resolver pull request #11
Opened 2024-03-13 20:12 UTC by lotharking

add handle responde and column logourl

2024-03-13 21:14 UTC, genaris requested changes
Pretty nice! I left some comments regarding the return status code for empty collections

2024-03-13 21:14 UTC, genaris commented on src/controllers/dto/service/createService.dto.ts
> +  @IsNotEmpty()
This should be optional

2024-03-13 21:14 UTC, genaris commented on src/controllers/serviceProvider.controller.ts
> +      const body = await this.serviceProviderService.findAll();
IMHO it is fine to return a 200 status code along with an empty array ([]) when no items are present, because the collection does exist (it's just that it's empty right now)

2024-03-13 22:43 UTC, lotharking commented on src/controllers/dto/service/createService.dto.ts
> +  @IsNotEmpty()
solved

2024-03-13 22:43 UTC, lotharking commented on src/controllers/serviceProvider.controller.ts
> +      const body = await this.serviceProviderService.findAll();
its true, solved

2024-03-14 12:51 UTC, genaris requested changes
Besides the error regarding mandatory logoUrl, if I attempt to create a service whose serviceProvider does not exist, it responds with a 404 error and a message like the following:

```json
{
  "message": "Service provider not found"
}
``` 

The message is fine but I don't think it is correct to return a 404 in that case. Not sure what's the best status code for that but for instance 422 seems more appropriate.

2024-03-14 14:38 UTC, genaris approved these changes

2024-03-14 14:39 UTC, merged